<?php

/**
 * PluginsiGaTopContentSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsiGaTopContentSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsiGaTopContentSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsiGaTopContentSlot');
    }
}